### PR TITLE
Update package dependencies

### PR DESCRIPTION
**Pull request by purcell**
See https://github.com/milkypostman/melpa/pull/1380 and #5

### CODE REVIEW

**Comment by yasuyk** [comment]
Ping :-)

**Comment by coventry** [comment]
Hi, Yasuyuki.  Thank you for following up.  Please ping me again on 
Friday, as I will have more time to look into it then.

I'm curious about how you're interested in using it.

Best regards,
Alex

**Comment by yasuyk** [comment]
@coventry OK. I will ping you on Friday. 

> I'm curious about how you're interested in using it.

Because I send a PR for `troncle.el` to MELPA (See https://github.com/milkypostman/melpa/pull/1380), and the PR is pending due to this issue.

**Comment by yasuyk** [comment]
@coventry Ping ;-)

**Comment by coventry** [comment]
Thanks for the ping, Yasuyuki.  Last weekend I was ill.  Will try to get to it this weekend.

**Comment by yasuyk** [comment]
@coventry  Take care of yourself.

**Pull request closed without merging**
